version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "serve -d postgres"
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - db
  db:
    restart: always
    environment:
      POSTGRES_PASSWORD: root123
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "50000:5432"
